language: node_js
node_js:
   - "12"
sudo: required
services:
   - docker

before_install:
   - docker build -t travis_deneme .

script:
   - docker run -e CI=true travis_deneme npm run test -- --coverage
     
deploy:
   edge: true     
   provider: elasticbeanstalk
   region: "eu-central-1"
   app: "docker-react"
   env: "DockerReact-env"
   bucket_name: "elasticbeanstalk-eu-central-1-376058719864"
   bucket_path: "docker-react"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: "$AWS_SECRET"

after_deploy:
   - echo "za"
